### ISSUE TITLE
Question: Notification Badge

### ISSUE THREAD

**Issue by anshul-kai** [sheshbabu/RNLocalScheduledNotificationDemo#1]
Thanks for creating this demo project. It took me a long time to realize that one doesn't need to request permissions on Android and thus the workflow is much different than iOS.

I have notifications working now but my notification icon shows up with an empty badge whereas you have a little white robot on the bottom right. I investigated the code and couldn't locate where this is setup. Would you be able to point me in the right direction?

**Comment by sheshbabu** [comment]
Hey @a-koka, did you try adding the icons in the res folder? https://github.com/sheshbabu/NewAnimeEpisodeNotifier/commit/911a831b115455eb195b7f2c43f1380e1726771b

**Comment by anshul-kai** [comment]
That did the trick. Thank you! Is `ic_notification` hardcoded in `react-native-push-notification` or is this an Android naming convention?

**Comment by sheshbabu** [comment]
I think it's an Android naming convention
